### ISSUE TITLE
Add cross-platform support

### ISSUE THREAD

**Issue by xunzixunzi** [cyrusbehr/tensorrt-cpp-api#18]
Hey @cyrusbehr, I have successfully used your project on Windows 10, and I am eager to contribute to this project.

The project is useful, but it is not convenient when I integrate it into my project. To make it more user-friendly, I plan to modify the CMakeLists.txt and some functions. If you are okay with these changes, I will clean up my code and submit a pull request.

The compilation environment is as follows:
- Visual Studio 2017/2022
- C++ 11
- CUDA 11.8
- cudnn 8.8.1.3
- OpenCV 4.7.0
- TensorRT 8.6.1.6

I conducted separate tests for semantic segmentation and object detection. Only the semantic segmentation using INT8 presision failed. You can find more details in the YOLOv8-TensorRT-CPP project's issue.

By the way, I am not a native English speaker. This issue may contain grammar errors. If there are any parts that are difficult to understand or if there are any mistakes, please let me know. This can also help me improve my English.

**Comment by cyrusbehr** [comment]
Hi there, yes you are more than welcome to contribute, I will give you credit in the readme as a collaborator. Please open up a PR

**Comment by xunzixunzi** [comment]
I was in a rush when I used it previously, so now I need to take some time to complete the code cleanup.

**Comment by cyrusbehr** [comment]
For sure, take your time.

**Comment by cyrusbehr** [comment]
Hey, any updates on this?

**Comment by xunzixunzi** [comment]
Yes, but I have been really busy with work these days, so I have not had the time to do thorough testing and write documentation. Perhaps I can submit a PR first and work on these tasks later？

**Comment by cyrusbehr** [comment]
Going to close this issue this the PR is up: https://github.com/cyrusbehr/tensorrt-cpp-api/pull/19

I still need to review the PR and integrate the changes.
