### ISSUE TITLE
share onnx and engine files for sanity check

### ISSUE THREAD

**Issue by ghost** [cyrusbehr/tensorrt-cpp-api#2]
Hi, thanks for the great work. Would it be possible to share the onnx and engine files used in this exercise. This would help us with sanity check. Thank you very much.

**Comment by cyrusbehr** [comment]
Hi there, sorry this has taken so long. Please see section titled [Sanity check](https://github.com/cyrusbehr/tensorrt-cpp-api#sanity-check) in the README file.
