### ISSUE TITLE
cannot convert argument 1 from 'const std::filesystem::path' to 'std::initializer_list<_Elem>'

### ISSUE THREAD

**Issue by Lakshyadevelops** [cyrusbehr/tensorrt-cpp-api#23]
Error in Engine.cpp because we cannot convert from filesystem::path to std::string type.
Just modifying Line 17 to `filepaths.emplace_back(entry.path().string());` resolves it.
This maybe a windows only problem.

**Comment by cyrusbehr** [comment]
Yeah likely an issue with the Window's build. I still haven't added full support for windows. That being said, I made the fix: https://github.com/cyrusbehr/tensorrt-cpp-api/commits/main
