### ISSUE TITLE
Cuda declarations were not declared in this scope for all the cuda commands

### ISSUE THREAD

**Issue by mathanprasannakumar** [cyrusbehr/tensorrt-cpp-api#24]
Hey @cyrusbehr ,
Thank you for this awesome work,
I was using this library, while compiling using make , for all the cuda commands i am getting error. Please help me i am stuck here.

Is there any cuda include location needs to be changed for the target  in the default CMakeLists.txt ? 

![Screenshot from 2023-10-09 17-19-57](https://github.com/cyrusbehr/tensorrt-cpp-api/assets/106004161/5b1e70a5-1ca7-437c-952c-0fe94973dedb)
![Screenshot from 2023-10-09 17-19-45](https://github.com/cyrusbehr/tensorrt-cpp-api/assets/106004161/96f776bc-7877-4a12-8a74-6330871c7f92)

Please let me know if you require further information

**Comment by mathanprasannakumar** [comment]
@cyrusbehr , My system configuration,

Ubuntu : 20.4
Cuda : 10.2.3
Cudnn : 8.2.1
Tensorrt  : 8.0.1.6
Open cv : 4.8.0 with Cuda

**Comment by cyrusbehr** [comment]
Can you please let me know if adding `#include "cuda_runtime.h"` to the top of engine.cpp fixes the issue?

**Comment by cyrusbehr** [comment]
Can you try compiling with CUDA 11 instead of CUDA 10 and see if that solves the issue? You can try doing so in a docker container so that you avoid messing with your system cuda.

**Comment by mathanprasannakumar** [comment]
Hey @cyrusbehr , 
I solved this isssue, we can close this issue 

1) For my device , all the libraries and its corresponding header files are located under  differant locations, so i modified the CMakeLists.txt as per the library locations that i have in my device.
2) Included `#include<cuda_runtime.h>` in engine.h 
3)  My tensorrt version is 8.0.1.0 and cuda version is 10.2.3 , i followed @ltetrel his implementation, as his cuda version and tensorrt is closer to my device.

Now everything works, Thanks @cyrusbehr and @ltetrel for your valuable work

**Comment by cyrusbehr** [comment]
Ok glad you were able to resolve it. I added to cuda_runtime.h header to the engine.h file.
