### ISSUE TITLE
multi-stream inference

### ISSUE THREAD

**Issue by lizexu123** [cyrusbehr/tensorrt-cpp-api#28]
Hello, does enqueueV3 support multi-stream inference? Is this part included in your code?

**Comment by cyrusbehr** [comment]
According to [this](https://forums.developer.nvidia.com/t/inference-time-when-using-multi-stream-in-tensorrt-is-much-slower-than-a-single-one/208292/6?u=cyrus.behr) it should be possible, but you'd need to create a  `IExecutionContext` for each stream. In the case of my code, you'd basically just create an instance of the `Engine` class for each model you want to run in parallel. However, do realize that you will have GPU contention if running models in parallel and not in serial.

**Comment by lizexu123** [comment]
> 据此[，](https://forums.developer.nvidia.com/t/inference-time-when-using-multi-stream-in-tensorrt-is-much-slower-than-a-single-one/208292/6?u=cyrus.behr)这应该是可能的，但是您需要 `IExecutionContext`为每个流创建一个。就我的代码而言，您基本上只需`Engine`为要并行运行的每个模型创建该类的实例。但是，请注意，如果并行而不是串行运行模型，将会出现 GPU 争用。


Can multiple cuda streams be provided to achieve multi-stream execution?
