### ISSUE TITLE
dynamic shape 

### ISSUE THREAD

**Issue by lizexu123** [cyrusbehr/tensorrt-cpp-api#29]

**Comment by cyrusbehr** [comment]
Hey, as of right now, this implementation does not support models with dynamic width and heights, only dynamic batch: 
![image](https://github.com/cyrusbehr/tensorrt-cpp-api/assets/17056751/d307c84c-120f-4262-b092-b60817f8af1f)

**Comment by lizexu123** [comment]
I borrowed a little bit and changed the inputDims, because if it is changed to another model, its input dimension is not necessarily 4.
![image](https://github.com/cyrusbehr/tensorrt-cpp-api/assets/39205361/81e51133-c447-4ef5-97d9-f64fc9b75e6e)
Do you think this is suitable for the input of any model? optim_input_shape() is the optimal input under dynamic_shape. Isn’t there min_input_shape and max_input_shape? This is the only way I can get the real input shape of the model without having a dimension of -1. Condition

**Comment by cyrusbehr** [comment]
Hi @Lishumuzixin 
Please look at v4.1. I have added support for fixed batch size > 1.
