### ISSUE TITLE
[feature] add support for and test with CUDA 12 Ubuntu 22.04 

### ISSUE THREAD

**Issue by cyrusbehr** [cyrusbehr/tensorrt-cpp-api#40]
Latest OpenCV as well

**Comment by huynhkhoa44** [comment]
I am using your github and having some problems. I have fully installed the required libraries, and of course tensorRT using the commands "pip install tensorrt, pip install tensorrt_lean and pip install tensorrt_dispatch". My version is ubuntu 22.04 and cuda 12.2. However, when I go to cmake .. I get an error "Could NOT find TensorRT (missing: TensorRT_LIBRARY TensorRT_INCLUDE_DIR)". How do I fix this error? Thank you very much

**Comment by cyrusbehr** [comment]
@huynhkhoa44 did you see the TODO in the CMakeLists.txt file? You probably forgot to specify the path to TensorRT. Please be sure to read the project readme thoroughly.

**Comment by cyrusbehr** [comment]
Tested and confirmed working on Ubuntu 22.04 with CUDA 12.0, cuDNN 8.9, and gcc 11.4
