### ISSUE TITLE
[feature] Use GpuMat buffer as input to TensorRT instead of copying GPU memory. 

### ISSUE THREAD

**Issue by eshafeeqe** [cyrusbehr/tensorrt-cpp-api#43]
First of all thanks for open sourcing this project. Learned lots of things from this code. 

This is not an issue but more like a doubt came to my mind when I looked through your code. I can see you done all the preprocessing steps in the GpuMat and then you copy the memory from GpuMat to device memory input buffer. I am wondering whether we can use the pointer to the GpuMat directly there and remove the memcopy operation ? Is there any reason for you doing this way ?

**Comment by cyrusbehr** [comment]
Hi. Yes it can be done. It just requires the code to be reworked a bit.
