### ISSUE TITLE
undefined symbol: _ZN5pwgen18nvrtcCreateProgramE

### ISSUE THREAD

**Issue by toystorynova** [cyrusbehr/tensorrt-cpp-api#44]
Followed readme and ran it, but it won't start due to the following error:

/home/toystorynova/Desktop/YOLOv8-TensorRT-CPP/cmake-build-debug/detect_object_image: symbol lookup error: /usr/local/cuda/targets/x86_64-linux/lib/libnvinfer_plugin.so.8: undefined symbol: _ZN5pwgen18nvrtcCreateProgramE

Currently using CUDA 12.1, Tensor 8.6 GA, and Ubuntu 22.04.3 LTS, could this be related to https://github.com/cyrusbehr/tensorrt-cpp-api/issues/40?

**Comment by cyrusbehr** [comment]
Please see my comment in the linked issue.
