### ISSUE TITLE
half precision returns nan for the feature values

### ISSUE THREAD

**Issue by sammilei** [cyrusbehr/tensorrt-cpp-api#47]
Hi, I am adapting the code for the half precision model. The code runs without error with configuration with fp16. Dimension of input and output are correct too so not buffer issues. However, the feature printout are all `nan`. Do you have any ideas? Thank you!

**Comment by cyrusbehr** [comment]
If the model takes FP16 inputs and outputs, then you need to convert your IO buffers from FP32 to FP16 with a CUDA kernel.
