### ISSUE TITLE
[feature] Add support for loading TensorRT engine file directly (instead of onnx model) 

### ISSUE THREAD

**Issue by IamShubhamGupto** [cyrusbehr/tensorrt-cpp-api#49]
Hello!

Thank you for the amazing guide to run onxx files in cpp. I see the code is also converting to tensorrt. Can we have support where we directly load tensorrt files and execute? thanks

**Comment by cyrusbehr** [comment]
Implemented in https://github.com/cyrusbehr/tensorrt-cpp-api/pull/53
