### ISSUE TITLE
How does this pointer get deleted?

### ISSUE THREAD

**Issue by Mona77** [cyrusbehr/tensorrt-cpp-api#50]
Thanks a lot of sharing your repository. 
Do you know how this pointer can be deleted?
```
IOptimizationProfile *optProfile = builder->createOptimizationProfile();
```
https://github.com/cyrusbehr/tensorrt-cpp-api/blob/main/src/engine.cpp#L126

**Comment by cyrusbehr** [comment]
See `NvInfer.h`

The builder retains ownership. 

![image](https://github.com/cyrusbehr/tensorrt-cpp-api/assets/17056751/cb6546d0-45e7-4e0a-a61b-ca76595b3eae)
