### ISSUE TITLE
CUDA version

### ISSUE THREAD

**Issue by yuanhs1996** [cyrusbehr/tensorrt-cpp-api#65]
Hello, can programs run with CUDA version 10.2?

**Comment by cyrusbehr** [comment]
Project requires TensorRT 10, which only supports CUDA 11 and 12 (CUDA 10 dropped in TRT 8), so no it's not supported. 
![image](https://github.com/cyrusbehr/tensorrt-cpp-api/assets/17056751/22bd546e-445d-48e1-83aa-1a3819c9887b)
