### ISSUE TITLE
Consider Integrating CodeRabbit.ai for Enhanced Code Quality

### ISSUE THREAD

**Issue by thomaskleiven** [cyrusbehr/tensorrt-cpp-api#70]
To reduce potential bugs and increase code quality, let's consider integrating [CodeRabbit.ai](https://coderabbit.ai/). Although I haven't used it extensively, it has provided valuable comments and suggestions in my experience.

**Tasks:**

- Explore CodeRabbit.ai and register the project.
- Follow their integration guide to set it up with the repository.

**Benefits:**
- Automated code reviews
- Enhanced code quality
- Free for open source projects

**Comment by cyrusbehr** [comment]
Sure 👍

**Comment by thomaskleiven** [comment]
Let's do this later at some point.
