### ISSUE TITLE
Multiple engines in multiple threads

### ISSUE THREAD

**Issue by mostafajalal20** [cyrusbehr/tensorrt-cpp-api#85]
Hi, I wrapped your main file into a class and created 4 objects, each running in separate threads. However, I have doubts that the GPU processes are truly running in parallel because when I increase the feeding rate to the engines, the memory usage keeps increasing until it's full. Is there any specific configuration or changes in code for support this?

**Comment by thomaskleiven** [comment]
You shouldn't need code changes for multithreading, but GPU memory is shared between threads, so high feeding rates can cause memory saturation.

**Comment by mostafajalal20** [comment]
Thanks for your hint! Do you have any suggestions for handling this on a GPU? Any extra code or changes needed?

**Comment by thomaskleiven** [comment]
No code changes should be necessary in my opinion. It is possible to just wrap the engine class and run it in a multithreaded environment. I would check these things first:

- Ensure your models and data fit within the GPU's memory limits.
- Make sure you're properly freeing up memory to avoid leaks.
- Use CUDA streams if possible: They can help manage multiple tasks on the GPU more efficiently.
