### ISSUE TITLE
[Question] Proper Way to Use Dynamic Batch Input Size.

### ISSUE THREAD

**Issue by abysslover** [cyrusbehr/tensorrt-cpp-api#86]
Dear @cyrusbehr,

First of all, thank you for sharing such an excellent library as open-source software. Your work is truly appreciated, and it's been incredibly helpful for our projects.

[Issue Overview] I am working with a model that supports a batch size of N, and currently, I am testing with N=2 to evaluate dynamic batch input. It is important to note that the process runs without issues when the batch size is set to 1. Below are the options I am using for configuration:

```cpp
Options options;
options.optBatchSize = 2;
options.maxBatchSize = 2;
```

[Problem] When I attempt to process two images simultaneously, I encounter the following error:

```
[error] IExecutionContext::enqueueV3: Error Code 1: Cuda Runtime (invalid argument)
```
[Preprocessing Code] Here is how the preprocessing is being performed. The gpuImgs vector contains two cv::cuda::GpuMat images that have been uploaded to GPU memory:

```cpp
std::vector<std::vector<cv::cuda::GpuMat>> XXXX::preprocess_batch(const std::vector<cv::cuda::GpuMat>& gpuImgs) 
{
    const auto& inputDims = m_trtEngine->getInputDims();
    input_model_width = inputDims[0].d[2];
    input_model_height = inputDims[0].d[1];

    // Initialize the batch container
    std::vector<std::vector<cv::cuda::GpuMat>> batchInputs(1); // Outer vector size is always 1

    // Process each image
    for (const auto& gpuImg : gpuImgs) {
        cv::cuda::GpuMat rgbMat;
        cv::cuda::cvtColor(gpuImg, rgbMat, cv::COLOR_BGR2RGB);

        m_original_image_height = gpuImg.rows;
        m_original_image_width = gpuImg.cols;

        // Resize if necessary
        auto resized = rgbMat;
        if (resized.rows != input_model_height || resized.cols != input_model_width) {
            resized = Engine<float>::resize(rgbMat, input_model_height, input_model_width);
        }

        // Add the processed image to the batch
        batchInputs[0].emplace_back(std::move(resized));
    }

    return batchInputs;
}
```
I also referred to issue #80, but it seems that the TensorRT version I am using (10.2.0.19) does not support the binding-related API suggested there.

[Question] Could you please guide me on how to modify my approach or code to correctly process a dynamic batch of images? Any insights or suggestions would be greatly appreciated.

Thank you for your time and support.

Best regards,

**Comment by abysslover** [comment]
I discovered a solution to the problem I was experiencing. My model initially runs with a batch size of 1, and after some time, it increases to 2, which causes issues. Therefore, I've modified the code to wait until the batch size reaches 2 before starting inference. This change prevents any problems from occurring.

However, if there's a way to dynamically adjust the input size while maintaining functionality, I would appreciate any guidance on how to implement that.

**Comment by abysslover** [comment]
After some more tests, I've found that all the output values become zeros with the above mentioned solution. Thus, I do not know where to fix for populating the proper outputs for each batch..

**Comment by abysslover** [comment]
I finally confirm that the current implementation of the tensorrt-cpp-api does not correctly support dynamic output sizes, may be due to the changes in the TensorRT API.

**Comment by abysslover** [comment]
I finally found a solution.

**Comment by tannq-jo** [comment]
Hi @abysslover, could you please upload your solution codes for this issue? Thank you.
